# Generated by Django 6.0 on 2025-12-22 09:20

import django.db.models.deletion
import greenshan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['handled'], name='greenshan_c_handled_a63867_idx'), models.Index(fields=['created'], name='greenshan_c_created_006f45_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('corporate', 'Corporate'), ('motion', 'Motion Graphics'), ('documentary', 'Documentary'), ('social', 'Social Media'), ('advertisement', 'Advertisement'), ('branding', 'Branding'), ('other', 'Other')], db_index=True, max_length=120)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=greenshan.models.upload_to_project_cover)),
                ('description', models.TextField(blank=True)),
                ('experience_notes', models.TextField(blank=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-project_date', '-created'],
                'indexes': [models.Index(fields=['featured'], name='greenshan_p_feature_a95be6_idx'), models.Index(fields=['category'], name='greenshan_p_categor_c4ba4c_idx'), models.Index(fields=['created'], name='greenshan_p_created_95e296_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['visible'], name='greenshan_t_visible_0c42b3_idx'), models.Index(fields=['created'], name='greenshan_t_created_6a20c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=greenshan.models.upload_to_project_media)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='greenshan.project')),
            ],
            options={
                'ordering': ['order', 'created'],
                'indexes': [models.Index(fields=['order'], name='greenshan_p_order_cb1dab_idx'), models.Index(fields=['media_type'], name='greenshan_p_media_t_0a4089_idx')],
            },
        ),
    ]
