# Generated by Django 6.0.1 on 2026-01-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenshan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactrequest',
            name='greenshan_c_handled_a63867_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactrequest',
            name='greenshan_c_created_006f45_idx',
        ),
        migrations.RemoveIndex(
            model_name='testimonial',
            name='greenshan_t_visible_0c42b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='testimonial',
            name='greenshan_t_created_6a20c8_idx',
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20),
        ),
    ]
